# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oliver/Documents/School/Sophomore Year MIT/6.111/6111_Final_Project/IP_Generation_Vivado_Project/IP_Generation_Vivado_Project.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
# IP: The module: 'dsp_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oliver/Documents/School/Sophomore Year MIT/6.111/6111_Final_Project/IP_Generation_Vivado_Project/IP_Generation_Vivado_Project.gen/sources_1/ip/dsp_macro_0/dsp_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/oliver/Documents/School/Sophomore Year MIT/6.111/6111_Final_Project/IP_Generation_Vivado_Project/IP_Generation_Vivado_Project.srcs/sources_1/ip/dsp_macro_0/dsp_macro_0.xci
# IP: The module: 'dsp_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oliver/Documents/School/Sophomore Year MIT/6.111/6111_Final_Project/IP_Generation_Vivado_Project/IP_Generation_Vivado_Project.gen/sources_1/ip/dsp_macro_0/dsp_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
